name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "We appreciate your contribution and are excited to have you involved in the project. Your feedback helps us improve! Stay awesome and happy coding!"
        pr-message: "Thank you for taking the time to contribute—your efforts mean a lot to us! We’ll review it soon. Keep up the great work!"
